
manifest:
  defaults:
    remote: zephyrproject-rtos

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: ottojo
      url-base: https://github.com/ottojo

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.0.0
      import:

        name-allowlist:
          - cmsis
          - hal_xtensa
          - hal_espressif
          - hal
          - mbedtls
    - name: zephyr_fusb302b
      remote: ottojo
      revision: main
